# 04 Feature Engineering

In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
!pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in /opt/conda/lib/python3.12/site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy<2,>=1.11.4 in /opt/conda/lib/python3.12/site-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /opt/conda/lib/python3.12/site-packages (from imbalanced-learn) (1.7.2)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Downloading sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [imbalanced-learn][imbalanced-learn]
Successfully installed imbalanced-learn-0.14.1 sklearn-compat-0.1.5

In [9]:
bucket = "ads508-team-4-private"
input_path = f"s3://{bucket}/processed/combined_attrition_data.csv"

df = pd.read_csv(input_path)
df.head()

,Age,Attrition,Department,DistanceFromHome,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,MonthlyIncome,NumCompaniesWorked,OverTime,PerformanceRating,RelationshipSatisfaction,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion
0,41,Yes,Sales,1,1,2,Female,94,3,2,...,5993,8,Yes,3,1,0,1,6,4,0
1,49,No,Research & Development,8,2,3,Male,61,2,2,...,5130,1,No,4,4,3,3,10,7,1
2,37,Yes,Research & Development,2,4,4,Male,92,2,1,...,2090,6,Yes,3,2,3,3,0,0,0
3,33,No,Research & Development,3,5,4,Female,56,3,1,...,2909,1,Yes,3,3,3,3,8,7,3
4,27,No,Research & Development,2,7,1,Male,40,3,1,...,3468,9,No,3,4,3,3,2,2,2

In [10]:
df = df.drop(columns=["EmployeeNumber"], errors="ignore")

In [11]:
df["Attrition"] = df["Attrition"].map({"Yes": 1, "No": 0})
df["Attrition"].value_counts(normalize=True)

Attrition
0    0.805231
1    0.194769
Name: proportion, dtype: float64

In [12]:
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()
numeric_cols = df.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical columns:", categorical_cols)
print("Numeric columns:", numeric_cols)

Categorical columns: ['Department', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']
Numeric columns: ['Age', 'Attrition', 'DistanceFromHome', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'NumCompaniesWorked', 'PerformanceRating', 'RelationshipSatisfaction', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion']

In [13]:
# create income buckets
df["IncomeCategory"] = pd.qcut(
    df["MonthlyIncome"],
    q=3,
    labels=["Low", "Medium", "High"]
)

In [14]:
# create tenure group 
df["TenureCategory"] = pd.cut(
    df["YearsAtCompany"],
    bins=[-1, 2, 5, 10, 100],
    labels=["0-2 years", "3-5 years", "6-10 years", "10+ years"]
)

In [15]:
# create promotion flag
df["NoRecentPromotion"] = np.where(df["YearsSinceLastPromotion"] >= 3, 1, 0)

In [16]:
df[["MonthlyIncome", "IncomeCategory", "YearsAtCompany", "TenureCategory", "YearsSinceLastPromotion", "NoRecentPromotion"]].head()

,MonthlyIncome,IncomeCategory,YearsAtCompany,TenureCategory,YearsSinceLastPromotion,NoRecentPromotion
0,5993,Low,6,6-10 years,0,0
1,5130,Low,10,6-10 years,1,0
2,2090,Low,0,0-2 years,0,0
3,2909,Low,8,6-10 years,3,1
4,3468,Low,2,0-2 years,2,0

In [17]:
#one hot encode variable
df_model = pd.get_dummies(df, drop_first=True)
df_model.head()

,Age,Attrition,DistanceFromHome,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,...,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes,IncomeCategory_Medium,IncomeCategory_High,TenureCategory_3-5 years,TenureCategory_6-10 years,TenureCategory_10+ years
0,41,1,1,2,94,3,2,4,5993,8,...,True,False,False,True,True,False,False,False,True,False
1,49,0,8,3,61,2,2,2,5130,1,...,False,False,True,False,False,False,False,False,True,False
2,37,1,2,4,92,2,1,3,2090,6,...,False,False,False,True,True,False,False,False,False,False
3,33,0,3,4,56,3,1,3,2909,1,...,False,False,True,False,True,False,False,False,True,False
4,27,0,2,1,40,3,1,2,3468,9,...,False,False,True,False,False,False,False,False,False,False

In [18]:
#seperate test variable
X = df_model.drop(columns=["Attrition"])
y = df_model["Attrition"]

In [19]:
#Split into train (80%) and temp (20%)
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Split temp into validation (10%) and test (10%)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,  
    random_state=42,
    stratify=y_temp
)

In [22]:
smote = SMOTE(random_state=1)

X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [24]:
print("Train:", y_train_resampled.value_counts(normalize=True))
print("Validation:", y_val.value_counts(normalize=True))
print("Test:", y_test.value_counts(normalize=True))

Train: Attrition
1    0.5
0    0.5
Name: proportion, dtype: float64
Validation: Attrition
0    0.804708
1    0.195292
Name: proportion, dtype: float64
Test: Attrition
0    0.80558
1    0.19442
Name: proportion, dtype: float64

### Save data

In [25]:
bucket = "ads508-team-4-private"

# Train (Original)
train_original_df = X_train.copy()
train_original_df["Attrition"] = y_train

# Train (SMOTE)
train_smote_df = pd.DataFrame(X_train_resampled, columns=X_train.columns)
train_smote_df["Attrition"] = y_train_resampled

# Validation
val_df = X_val.copy()
val_df["Attrition"] = y_val

# Test
test_df = X_test.copy()
test_df["Attrition"] = y_test

# Paths
train_smote_path = f"s3://{bucket}/processed/train_attrition_smote.csv"
val_path = f"s3://{bucket}/processed/validation_attrition_data.csv"
test_path = f"s3://{bucket}/processed/test_attrition_data.csv"
train_original_path = f"s3://{bucket}/processed/train_attrition_original.csv"
train_original_df.to_csv(train_original_path, index=False)

# Save to S3
train_smote_df.to_csv(train_smote_path, index=False)
val_df.to_csv(val_path, index=False)
test_df.to_csv(test_path, index=False)

print(train_smote_path)
print(val_path)
print(test_path)
print(train_original_path)

s3://ads508-team-4-private/processed/train_attrition_smote.csv
s3://ads508-team-4-private/processed/validation_attrition_data.csv
s3://ads508-team-4-private/processed/test_attrition_data.csv
s3://ads508-team-4-private/processed/train_attrition_original.csv